services:
  app:
    build:
      context: ./php-fpm
    container_name: ci3_php
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  web:
    image: nginx:latest
    container_name: ci3_nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: ci3_mysql
    environment:
      MYSQL_DATABASE: ci3db
      MYSQL_USER: ci3user
      MYSQL_PASSWORD: ci3pass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
